steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
    - '--build-arg'
    - 'REACT_APP_DATASOURCE=places.json'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'beta', 'run', 'deploy', '--region', 'europe-west1', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME', '--platform', 'managed', '--allow-unauthenticated', '$REPO_NAME-$BRANCH_NAME' ]
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME'
